package HelloWorld;


/**
* HelloWorld/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../helloworld.idl
* 11 Ноябрь 2011 г. 19:12:41 GMT+04:00
*/

public interface HelloOperations 
{
  String world (String name);
} // interface HelloOperations
