package HelloWorld;

/**
* HelloWorld/HelloHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../helloworld.idl
* 11 Ноябрь 2011 г. 19:12:41 GMT+04:00
*/

public final class HelloHolder implements org.omg.CORBA.portable.Streamable
{
  public HelloWorld.Hello value = null;

  public HelloHolder ()
  {
  }

  public HelloHolder (HelloWorld.Hello initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HelloWorld.HelloHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HelloWorld.HelloHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HelloWorld.HelloHelper.type ();
  }

}
