package HelloWorld;


/**
* HelloWorld/Hello.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../helloworld.idl
* 11 Ноябрь 2011 г. 19:12:41 GMT+04:00
*/

public interface Hello extends HelloOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Hello
