######################################################################
# Automatically generated by qmake (1.07a) Sun Nov 25 22:17:46 2007
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += . ../common

# Input
SOURCES += main.cpp
LIBS += -L../common -lcommon
