/*
 * AddFormatDialog.java
 *
 * Created on May 22, 2009, 6:19 PM
 */

package admintool;

/**
 *
 * @author  bondin
 */
public class AddFormatDialog extends javax.swing.JDialog {

    /** Creates new form AddFormatDialog */
    public AddFormatDialog(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
        setLocationRelativeTo(parent);
        m_format = null;
        
        return;
    }

    public admintool.entity.Format showDialog() {
        m_formatPane.setFormat(new admintool.entity.Format());
        m_format = null;
        setVisible(true);
        return m_format;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        m_formatPane = new admintool.FormatPane();
        m_buttonsPane = new javax.swing.JPanel();
        m_okButton = new javax.swing.JButton();
        m_cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        m_formatPane.setShowButtons(false);
        m_formatPane.setShowTimes(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        getContentPane().add(m_formatPane, gridBagConstraints);

        m_buttonsPane.setLayout(new java.awt.GridBagLayout());

        m_okButton.setText("Создать");
        m_okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_okButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        m_buttonsPane.add(m_okButton, gridBagConstraints);

        m_cancelButton.setText("Отмена");
        m_cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_cancelButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        m_buttonsPane.add(m_cancelButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(m_buttonsPane, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void m_okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_okButtonActionPerformed
    m_format = m_formatPane.getFormat();
    dispose();
}//GEN-LAST:event_m_okButtonActionPerformed

private void m_cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_cancelButtonActionPerformed
    m_format = null;
    dispose();
}//GEN-LAST:event_m_cancelButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel m_buttonsPane;
    private javax.swing.JButton m_cancelButton;
    private admintool.FormatPane m_formatPane;
    private javax.swing.JButton m_okButton;
    // End of variables declaration//GEN-END:variables

    private admintool.entity.Format m_format;
           
}
