#include<stdio.h>

char * ru2trans_tbl[256];

int main(int argc, char ** argv)
{
  int i;
  
  for(i=0; i<256; i++)
  {
    ru2trans_tbl[i] = NULL;
  }
  
  ru2trans_tbl[(unsigned char) 'Á'] = "a";
  ru2trans_tbl[(unsigned char) 'Â'] = "b";
  ru2trans_tbl[(unsigned char) '×'] = "v";
  ru2trans_tbl[(unsigned char) 'Ç'] = "g";
  ru2trans_tbl[(unsigned char) 'Ä'] = "d";
  ru2trans_tbl[(unsigned char) 'Å'] = "e";
  ru2trans_tbl[(unsigned char) '£'] = "yo";
  ru2trans_tbl[(unsigned char) 'Ö'] = "zh";
  ru2trans_tbl[(unsigned char) 'Ú'] = "z";
  ru2trans_tbl[(unsigned char) 'É'] = "i";
  ru2trans_tbl[(unsigned char) 'Ê'] = "y";
  ru2trans_tbl[(unsigned char) 'Ë'] = "k";
  ru2trans_tbl[(unsigned char) 'Ì'] = "l";
  ru2trans_tbl[(unsigned char) 'Í'] = "m";
  ru2trans_tbl[(unsigned char) 'Î'] = "n";
  ru2trans_tbl[(unsigned char) 'Ï'] = "o";
  ru2trans_tbl[(unsigned char) 'Ğ'] = "p";
  ru2trans_tbl[(unsigned char) 'Ò'] = "r";
  ru2trans_tbl[(unsigned char) 'Ó'] = "s";
  ru2trans_tbl[(unsigned char) 'Ô'] = "t";
  ru2trans_tbl[(unsigned char) 'Õ'] = "u";
  ru2trans_tbl[(unsigned char) 'Æ'] = "f";
  ru2trans_tbl[(unsigned char) 'È'] = "h";
  ru2trans_tbl[(unsigned char) 'Ã'] = "ts";
  ru2trans_tbl[(unsigned char) 'Ş'] = "ch";
  ru2trans_tbl[(unsigned char) 'Û'] = "sh";
  ru2trans_tbl[(unsigned char) 'İ'] = "sch";
  ru2trans_tbl[(unsigned char) 'ß'] = "";
  ru2trans_tbl[(unsigned char) 'Ù'] = "y";
  ru2trans_tbl[(unsigned char) 'Ø'] = "";
  ru2trans_tbl[(unsigned char) 'Ü'] = "e";
  ru2trans_tbl[(unsigned char) 'À'] = "yu";
  ru2trans_tbl[(unsigned char) 'Ñ'] = "ya";

  ru2trans_tbl[(unsigned char) 'á'] = "A";
  ru2trans_tbl[(unsigned char) 'â'] = "B";
  ru2trans_tbl[(unsigned char) '÷'] = "V";
  ru2trans_tbl[(unsigned char) 'ç'] = "G";
  ru2trans_tbl[(unsigned char) 'ä'] = "D";
  ru2trans_tbl[(unsigned char) 'å'] = "E";
  ru2trans_tbl[(unsigned char) '³'] = "YO";
  ru2trans_tbl[(unsigned char) 'ö'] = "ZH";
  ru2trans_tbl[(unsigned char) 'ú'] = "Z";
  ru2trans_tbl[(unsigned char) 'é'] = "I";
  ru2trans_tbl[(unsigned char) 'ê'] = "Y";
  ru2trans_tbl[(unsigned char) 'ë'] = "K";
  ru2trans_tbl[(unsigned char) 'ì'] = "L";
  ru2trans_tbl[(unsigned char) 'é'] = "M";
  ru2trans_tbl[(unsigned char) 'î'] = "N";
  ru2trans_tbl[(unsigned char) 'ï'] = "O";
  ru2trans_tbl[(unsigned char) 'ğ'] = "P";
  ru2trans_tbl[(unsigned char) 'ò'] = "R";
  ru2trans_tbl[(unsigned char) 'ó'] = "S";
  ru2trans_tbl[(unsigned char) 'ô'] = "T";
  ru2trans_tbl[(unsigned char) 'õ'] = "U";
  ru2trans_tbl[(unsigned char) 'æ'] = "F";
  ru2trans_tbl[(unsigned char) 'è'] = "H";
  ru2trans_tbl[(unsigned char) 'ã'] = "TS";
  ru2trans_tbl[(unsigned char) 'ş'] = "CH";
  ru2trans_tbl[(unsigned char) 'û'] = "SH";
  ru2trans_tbl[(unsigned char) 'ı'] = "SCH";
  ru2trans_tbl[(unsigned char) 'ÿ'] = "";
  ru2trans_tbl[(unsigned char) 'ù'] = "Y";
  ru2trans_tbl[(unsigned char) 'ø'] = "";
  ru2trans_tbl[(unsigned char) 'ü'] = "E";
  ru2trans_tbl[(unsigned char) 'à'] = "YU";
  ru2trans_tbl[(unsigned char) 'ñ'] = "YA";

  printf("/* ********************************************************* *\\\n");
  printf(" *\n");
  printf(" * FILE: ru2trans.c\n");
  printf(" *\n");
  printf(" * GENERATED BY mkru2trans at %s\n", __DATE__);
  printf(" *\n");
  printf("\\* ********************************************************* */\n");
  printf("\n");
  printf("char * ru2trans_tbl[] = { ");

  for(i=0; i<256; i++)
  {
    printf("\"");
    
    if(ru2trans_tbl[i] == NULL)
    {
      printf("\\%.3o", i);
    }
    else
    {
      printf("%s", ru2trans_tbl[i]);
    }
    
    printf("\"");
    
    if(i != 255)
    {
      printf(",\n                          ");
    }
  }

  printf(" };\n");
  
  return 0;
}
