#!/usr/bin/python

import glob;
import re;

class Application:
    pass

categories = { 'AudioVideo' : [],
               'Audio'      : [],
               'Video'      : [],
               'Development': [],
               'Education'  : [],
               'Game'       : [],
               'Graphics'   : [],
               'Network'    : [],
               'Office'     : [],
               'Settings'   : [],
               'System'     : [],
               'Utility'    : [] };

desktopFilesDirs = [ '/usr/share/applications',
                     '/usr/share/applications/kde' ];

desktopFiles = [];

for dir in desktopFilesDirs:
    desktopFiles += glob.glob(dir + '/*.desktop');

reName       = re.compile('^[ \t]*Name[ \t]*=[ \t]*');
reGenName    = re.compile('^[ \t]*GenericName[ \t]*=[ \t]*');
reIcon       = re.compile('^[ \t]*Icon[ \t]*=[ \t]*');
reExec       = re.compile('^[ \t]*Exec[ \t]*=[ \t]*');
reCategories = re.compile('^[ \t]*Categories[ \t]*=[ \t]*');
reSplit      = re.compile(';');
reNewLine    = re.compile('\n$');
reExecC      = re.compile('%c');
reExecI      = re.compile('%i');
reExecOther  = re.compile('%.');

for fil in desktopFiles:
    fp = open(fil, 'r');
    nameVal       = '';
    genNameVal    = '';
    iconVal       = '';
    execVal       = '';
    categoriesVal = '';
    for line in fp:
        if reName.match(line):
            nameVal = reNewLine.sub('', reName.sub('', line));
        if reGenName.match(line):
            genNameVal = reNewLine.sub('', reGenName.sub('', line));
        if reIcon.match(line):
            iconVal = reNewLine.sub('', reIcon.sub('', line));
        if reExec.match(line):
            execVal = reNewLine.sub('', reExec.sub('', line));
        if reCategories.match(line):
            categoriesVal = reNewLine.sub('', reCategories.sub('', line));
    fp.close();
    if nameVal == '' or execVal == '':
        continue;
    execVal = reExecC.sub(nameVal, execVal);
    if iconVal == '':
        execVal = reExecI.sub('', execVal);
    else:
        execVal = reExecI.sub('--icon ' + iconVal, execVal);
    execVal = reExecOther.sub('', execVal);
    categoriesList = reSplit.split(categoriesVal);
    for cat in categoriesList:
        if not categories.has_key(cat):
            continue;
        app = Application();
        if genNameVal == '':
            app.Name = nameVal;
        else:
            app.Name = nameVal + ', ' + genNameVal;
        app.Icon = iconVal;
        app.Exec = execVal;
        categories[cat].append(app);

print('# This file is autogenerated with icemenu.py script');
for cat in categories:
    print('menu "' + cat + '" afolder {');
    for app in categories[cat]:
        print('\tprog "' + app.Name + '" ' + app.Icon + " " + app.Exec);
    print('}');

exit (0);
