/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ElementChooserTestJFrame.java
 *
 * Created on 08.02.2010, 23:32:44
 */

package admintool.testing;

import java.util.Vector;

/**
 *
 * @author dbondin
 */
public class ElementChooserTestJFrame extends javax.swing.JFrame {

    /** Creates new form ElementChooserTestJFrame */
    public ElementChooserTestJFrame() {
        initComponents();
        Vector<String> elements = new Vector<String>();
        elements.add("element-1");
        elements.add("element-2");
        elements.add("element-3");
        elements.add("element-4");
        elementsChooser1.setElements(elements);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        elementsChooser1 = new admintool.ElementsChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(elementsChooser1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ElementChooserTestJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private admintool.ElementsChooser elementsChooser1;
    // End of variables declaration//GEN-END:variables

}
